### ISSUE TITLE
An error occurred 'ProfilePage'

### ISSUE THREAD

**Issue by 89z** [dzaytsev91/mygf-instagram#12]
Using this command:

~~~
python example.py srpen6 PASSWORD britneyspears
~~~

I get this result:

~~~
An error occurred 'ProfilePage'
~~~

**Comment by dzaytsev91** [comment]
@89z Looks like instagram changed they API, I will try to look at this as soon as possible

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/tree/master/instagram
