### ISSUE TITLE
thanks for the code

### ISSUE THREAD

**Issue by zzeesstt** [dzaytsev91/mygf-instagram#2]
Thanks for the code. But what if there are several girls?)

**Comment by dzaytsev91** [comment]
@zzeesstt Thank you for your issue. I didn't envisage such case, I'll make a fix as soon as possible :)

**Comment by zzeesstt** [comment]
Thanks you!)

**Comment by dzaytsev91** [comment]
@zzeesstt I updated the code, now you can pass any number of your girlfriends accounts with comma separated, I also updated README with some examples
