### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zzeesstt** [dzaytsev91/mygf-instagram#5]
С последним обновлением example.py, стала появляться синтаксическая ошибка в 16 линии.
  File "example.py", line 16
SyntaxError: invalid syntax

**Comment by dzaytsev91** [comment]
@zzeesstt wow, looks like the last merge wasn’t good, I’ll fix it today

**Comment by dzaytsev91** [comment]
@zzeesstt I updated the code, fixed this bug and change the way you run the code, check README.md for examples

**Comment by zzeesstt** [comment]
update - very coo! thank you so much)

**Comment by zzeesstt** [comment]
Very good code. Everything is super. That's only with some users working, and with some - no. For example, with "natelapankratovamamisashvili" does not work (


___
InstagramBot started at 03.11.2017 23:48:
(venv) pi@srv:~/mygf-instagram $
__

**Comment by dzaytsev91** [comment]
@zzeesstt Yep, that's because the account is closed from not followers, I am thinking how to fix this problem

**Comment by zzeesstt** [comment]
Understood, thanks)

**Comment by YurieCo** [comment]
the only one script where I could understand how does cockies is build
